<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <!--<TargetFramework>net481</TargetFramework>-->
	  <TargetFramework>net10.0-windows</TargetFramework>

	  <!--<RuntimeIdentifier>win-x64</RuntimeIdentifier>-->
	  <!--<SelfContained>false</SelfContained>-->
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <LangVersion>14.0</LangVersion>
    <MSBuildWarningsAsMessages>$(MSBuildWarningsAsMessages);MSB3277</MSBuildWarningsAsMessages>

  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="IKVM" Version="8.15.0" />
		<PackageReference Include="IKVM.Maven.Sdk" Version="1.11.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3967.48" />
		<PackageReference Include="WinSCP" Version="6.5.6" />
		
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ApacheMinaSSHD.NET.Bindings\ApacheMinaSSHD.NET.Bindings.csproj" />
	  <ProjectReference Include="..\ApacheMinaSSHD.NET.Wrapper\ApacheMinaSSHD.NET.Wrapper.csproj" />
	</ItemGroup>

</Project>
