version: 2
updates:
  - package-ecosystem: nuget
    directory: /ApacheMinaSSHD.NET.Bindings
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /ApacheMinaSSHD.NET.Wrapper
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /Sample/SimpleSSHDSever
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
