$header = @'
// Copyright (c) 2026 SERALYNX LLC and ApacheMinaSSHD.NET contributors.
// Licensed under the MIT License. See LICENSE file in the repository root for full license text.
'@

$excludeDirs = @(
    '\obj\', '\bin\',
    '\.public-repo-staging\', '\.public-repo-staging-auth\'
)

$files = Get-ChildItem -Recurse -Filter *.cs -Path "$PSScriptRoot\.." |
    Where-Object {
        $path = $_.FullName
        -not ($excludeDirs | Where-Object { $path -match [regex]::Escape($_) })
    }

$count = 0
foreach ($file in $files) {
    $content = Get-Content -LiteralPath $file.FullName -Raw
    if ($content -match '^// Copyright \(c\) 2026 SERALYNX LLC') {
        continue
    }
    # Skip auto-generated files
    if ($content -match '^// <auto-generated>') {
        continue
    }
    $newContent = $header + "`r`n" + $content
    Set-Content -LiteralPath $file.FullName -Value $newContent -NoNewLine
    $count++
}

Write-Output "Added license headers to $count files."
